# action.yml
name: Patchwork to PR

description: 'Create PR after reading the patch series from the Patchwork URL'

inputs:
  pw_key_str:
    description: kernel or user
    default: "kernel"
  base_branch:
    description: Branch name where the PR is pushed
    default: "workflow"
  github_token:
    description: Secret github token
    required: true
  email_token:
    description: Email token
    required: true
  patchwork_token:
    description: Patchwork token
    required: true
  config:
    description: Configuration file or remote file URL
    required: false
    default: /config.json
  patchwork_id:
    description: Patchwork project ID
    required: true
  email_message:
    description: File/URL containing email notification message
    required: false
    default: /default-email-message.txt
  user:
    description: Patchwork user ID
    required: false
    default: 104215

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}
    PATCHWORK_TOKEN: ${{ inputs.patchwork_token }}
  args:
    - ${{ inputs.pw_key_str }}
    - ${{ inputs.base_branch }}
    - ${{ inputs.config }}
    - ${{ inputs.patchwork_id }}
    - ${{ inputs.email_message }}
    - ${{ inputs.user }}

branding:
  icon: 'bluetooth'
  color: '#0082FC'
